"""rename department

Revision ID: dfc3c0a30a2b
Revises: fe92c2acf69e
Create Date: 2024-12-20 11:00:43.503356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc3c0a30a2b'
down_revision = 'fe92c2acf69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
